# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Build and deploy Node.js app to Azure Web App - phonebook

on:
  push:
    branches:
      - main
    paths:
      - 'part_0-7/part_3/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: part_0-7/part_3/package-lock.json
      
      - name: Install dependencies
        working-directory: part_0-7/part_3
        run: npm ci

      # Optional: Run build step if needed (skip if pure Node/Express)
      - name: Build app
        working-directory: part_0-7/part_3
        run: npm run build

      # Archive the app into a zip file
      - name: Archive app
        run: |
          cd part_0-7/part_3
          zip -r ../part_3.zip .
  
      - name: Upload artifact for deployment job (part_3 only)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-zip
          path: part_3.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      
      # Download zip artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0132532799F04B818670CB60BF48C9F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_980D92ED0BE24882B94CAF8F44D395DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F3B3F14F24C4AEF8036B3C3A8CDC0A6 }}

      # Deploy zip to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'phonebook'
          slot-name: 'Production'
          package: ./part_3.zip
    


          